In [14]:
import sys
import numpy
numpy.set_printoptions(threshold=False)

In [ ]:
def loop_laps_world(width, n_laps, stay_still=False):
    n_states = n_laps * (2 * width + 2 * (width - 2))

    adj = np.zeros((n_states, n_states))

    # go round track twice
    for i in range(n_states):
        if i < n_states - 1:
            adj[i, i + 1] = 1

        if stay_still:
            adj[i, i] = 1

    # lap to beginning:
    adj[n_states - 1, 0] = 1

    tran = np.zeros((n_states, n_states))
    for i in range(n_states):
        if sum(adj[i]) > 0:
            tran[i] = adj[i] / sum(adj[i])

    return adj, tran

In [45]:
def square_world(width, stay_still=False):
    """
        #state number counts accross then down
        a = np.asarray(range(25))
        print(a)
        print(np.reshape(a,(5,5)))
        [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
        [[ 0  1  2  3  4]
         [ 5  6  7  8  9]
         [10 11 12 13 14]
         [15 16 17 18 19]
         [20 21 22 23 24]]
    """
    states = int(width ** 2)
    adj = np.zeros((states, states))

    for i in range(states):
        # stay still
        if stay_still:
            adj[i, i] = 1
        # up - down
        if i + width < states:
            adj[i, i + width] = 1
            adj[i + width, i] = 1
            # left - right
        if np.mod(i, width) != 0:
            adj[i, i - 1] = 1
            adj[i - 1, i] = 1

    tran = np.zeros((states, states))
    for i in range(states):
        if sum(adj[i]) > 0:
            tran[i] = adj[i] / sum(adj[i])

    return adj, tran

In [56]:
size8_4Lap = loop_laps_world(3, 4)

False in (size8_4Lap[0] == size8_4Lap[1])

False

In [57]:
np.zeros(5) == np.zeros(5)

array([ True,  True,  True,  True,  True])

In [47]:
square_world(4, 4)[0]

array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 1., 1.]])

In [64]:
for num, i in enumerate([1, 2, 3, 4, 5][3:]):
    print(num + 3, i) 

3 4
4 5
